# Generated by Django 3.1.7 on 2021-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('team', '0002_auto_20211029_1418'),
        ('stadion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='matches',
            field=models.ManyToManyField(to='matches.Match'),
        ),
        migrations.AddField(
            model_name='stadion',
            name='teams',
            field=models.ManyToManyField(to='team.Team'),
        ),
    ]
