# Generated by Django 3.1.7 on 2021-10-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20211029_1418'),
        ('invites', '0002_auto_20211029_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='inviting_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_invites', to='team.team'),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='team_to_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviting_teams', to='team.team'),
        ),
    ]
