# Generated by Django 3.2.8 on 2021-10-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_id'),
        ('invites', '0005_auto_20211030_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='team_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invites.status'),
        ),
    ]
